//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace EccInfra
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class EccEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new EccEntities object using the connection string found in the 'EccEntities' section of the application configuration file.
        /// </summary>
        public EccEntities() : base("name=EccEntities", "EccEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new EccEntities object.
        /// </summary>
        public EccEntities(string connectionString) : base(connectionString, "EccEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new EccEntities object.
        /// </summary>
        public EccEntities(EntityConnection connection) : base(connection, "EccEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Usuarios> Usuarios
        {
            get
            {
                if ((_Usuarios == null))
                {
                    _Usuarios = base.CreateObjectSet<Usuarios>("Usuarios");
                }
                return _Usuarios;
            }
        }
        private ObjectSet<Usuarios> _Usuarios;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Encontros> Encontros
        {
            get
            {
                if ((_Encontros == null))
                {
                    _Encontros = base.CreateObjectSet<Encontros>("Encontros");
                }
                return _Encontros;
            }
        }
        private ObjectSet<Encontros> _Encontros;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Usuarios EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUsuarios(Usuarios usuarios)
        {
            base.AddObject("Usuarios", usuarios);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Encontros EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEncontros(Encontros encontros)
        {
            base.AddObject("Encontros", encontros);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EccModel", Name="Encontros")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Encontros : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Encontros object.
        /// </summary>
        /// <param name="encontroId">Initial value of the EncontroId property.</param>
        /// <param name="nome">Initial value of the Nome property.</param>
        /// <param name="eventoConfirmado">Initial value of the EventoConfirmado property.</param>
        /// <param name="eventoRealizado">Initial value of the EventoRealizado property.</param>
        /// <param name="qtdeCasais">Initial value of the QtdeCasais property.</param>
        public static Encontros CreateEncontros(global::System.Int32 encontroId, global::System.String nome, global::System.Boolean eventoConfirmado, global::System.Boolean eventoRealizado, global::System.Int32 qtdeCasais)
        {
            Encontros encontros = new Encontros();
            encontros.EncontroId = encontroId;
            encontros.Nome = nome;
            encontros.EventoConfirmado = eventoConfirmado;
            encontros.EventoRealizado = eventoRealizado;
            encontros.QtdeCasais = qtdeCasais;
            return encontros;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 EncontroId
        {
            get
            {
                return _EncontroId;
            }
            set
            {
                if (_EncontroId != value)
                {
                    OnEncontroIdChanging(value);
                    ReportPropertyChanging("EncontroId");
                    _EncontroId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("EncontroId");
                    OnEncontroIdChanged();
                }
            }
        }
        private global::System.Int32 _EncontroId;
        partial void OnEncontroIdChanging(global::System.Int32 value);
        partial void OnEncontroIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nome
        {
            get
            {
                return _Nome;
            }
            set
            {
                OnNomeChanging(value);
                ReportPropertyChanging("Nome");
                _Nome = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nome");
                OnNomeChanged();
            }
        }
        private global::System.String _Nome;
        partial void OnNomeChanging(global::System.String value);
        partial void OnNomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Local
        {
            get
            {
                return _Local;
            }
            set
            {
                OnLocalChanging(value);
                ReportPropertyChanging("Local");
                _Local = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Local");
                OnLocalChanged();
            }
        }
        private global::System.String _Local;
        partial void OnLocalChanging(global::System.String value);
        partial void OnLocalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DtInicial
        {
            get
            {
                return _DtInicial;
            }
            set
            {
                OnDtInicialChanging(value);
                ReportPropertyChanging("DtInicial");
                _DtInicial = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DtInicial");
                OnDtInicialChanged();
            }
        }
        private Nullable<global::System.DateTime> _DtInicial;
        partial void OnDtInicialChanging(Nullable<global::System.DateTime> value);
        partial void OnDtInicialChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DtFinal
        {
            get
            {
                return _DtFinal;
            }
            set
            {
                OnDtFinalChanging(value);
                ReportPropertyChanging("DtFinal");
                _DtFinal = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DtFinal");
                OnDtFinalChanged();
            }
        }
        private Nullable<global::System.DateTime> _DtFinal;
        partial void OnDtFinalChanging(Nullable<global::System.DateTime> value);
        partial void OnDtFinalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean EventoConfirmado
        {
            get
            {
                return _EventoConfirmado;
            }
            set
            {
                OnEventoConfirmadoChanging(value);
                ReportPropertyChanging("EventoConfirmado");
                _EventoConfirmado = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EventoConfirmado");
                OnEventoConfirmadoChanged();
            }
        }
        private global::System.Boolean _EventoConfirmado;
        partial void OnEventoConfirmadoChanging(global::System.Boolean value);
        partial void OnEventoConfirmadoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean EventoRealizado
        {
            get
            {
                return _EventoRealizado;
            }
            set
            {
                OnEventoRealizadoChanging(value);
                ReportPropertyChanging("EventoRealizado");
                _EventoRealizado = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EventoRealizado");
                OnEventoRealizadoChanged();
            }
        }
        private global::System.Boolean _EventoRealizado;
        partial void OnEventoRealizadoChanging(global::System.Boolean value);
        partial void OnEventoRealizadoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 QtdeCasais
        {
            get
            {
                return _QtdeCasais;
            }
            set
            {
                OnQtdeCasaisChanging(value);
                ReportPropertyChanging("QtdeCasais");
                _QtdeCasais = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("QtdeCasais");
                OnQtdeCasaisChanged();
            }
        }
        private global::System.Int32 _QtdeCasais;
        partial void OnQtdeCasaisChanging(global::System.Int32 value);
        partial void OnQtdeCasaisChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EccModel", Name="Usuarios")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Usuarios : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Usuarios object.
        /// </summary>
        /// <param name="idUsuario">Initial value of the IdUsuario property.</param>
        /// <param name="nome">Initial value of the Nome property.</param>
        /// <param name="isActive">Initial value of the IsActive property.</param>
        /// <param name="nivel">Initial value of the Nivel property.</param>
        public static Usuarios CreateUsuarios(global::System.Int32 idUsuario, global::System.String nome, global::System.Boolean isActive, global::System.Byte nivel)
        {
            Usuarios usuarios = new Usuarios();
            usuarios.IdUsuario = idUsuario;
            usuarios.Nome = nome;
            usuarios.IsActive = isActive;
            usuarios.Nivel = nivel;
            return usuarios;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdUsuario
        {
            get
            {
                return _IdUsuario;
            }
            set
            {
                if (_IdUsuario != value)
                {
                    OnIdUsuarioChanging(value);
                    ReportPropertyChanging("IdUsuario");
                    _IdUsuario = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdUsuario");
                    OnIdUsuarioChanged();
                }
            }
        }
        private global::System.Int32 _IdUsuario;
        partial void OnIdUsuarioChanging(global::System.Int32 value);
        partial void OnIdUsuarioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nome
        {
            get
            {
                return _Nome;
            }
            set
            {
                OnNomeChanging(value);
                ReportPropertyChanging("Nome");
                _Nome = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nome");
                OnNomeChanged();
            }
        }
        private global::System.String _Nome;
        partial void OnNomeChanging(global::System.String value);
        partial void OnNomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsActive
        {
            get
            {
                return _IsActive;
            }
            set
            {
                OnIsActiveChanging(value);
                ReportPropertyChanging("IsActive");
                _IsActive = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsActive");
                OnIsActiveChanged();
            }
        }
        private global::System.Boolean _IsActive;
        partial void OnIsActiveChanging(global::System.Boolean value);
        partial void OnIsActiveChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte Nivel
        {
            get
            {
                return _Nivel;
            }
            set
            {
                OnNivelChanging(value);
                ReportPropertyChanging("Nivel");
                _Nivel = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Nivel");
                OnNivelChanged();
            }
        }
        private global::System.Byte _Nivel;
        partial void OnNivelChanging(global::System.Byte value);
        partial void OnNivelChanged();

        #endregion

    
    }

    #endregion

    
}
