//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace EccInfra
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class EccEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new EccEntities object using the connection string found in the 'EccEntities' section of the application configuration file.
        /// </summary>
        public EccEntities() : base("name=EccEntities", "EccEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new EccEntities object.
        /// </summary>
        public EccEntities(string connectionString) : base(connectionString, "EccEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new EccEntities object.
        /// </summary>
        public EccEntities(EntityConnection connection) : base(connection, "EccEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Usuarios> Usuarios
        {
            get
            {
                if ((_Usuarios == null))
                {
                    _Usuarios = base.CreateObjectSet<Usuarios>("Usuarios");
                }
                return _Usuarios;
            }
        }
        private ObjectSet<Usuarios> _Usuarios;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Encontros> Encontros
        {
            get
            {
                if ((_Encontros == null))
                {
                    _Encontros = base.CreateObjectSet<Encontros>("Encontros");
                }
                return _Encontros;
            }
        }
        private ObjectSet<Encontros> _Encontros;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CasaisConvidadores> CasaisConvidadores
        {
            get
            {
                if ((_CasaisConvidadores == null))
                {
                    _CasaisConvidadores = base.CreateObjectSet<CasaisConvidadores>("CasaisConvidadores");
                }
                return _CasaisConvidadores;
            }
        }
        private ObjectSet<CasaisConvidadores> _CasaisConvidadores;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CasaisVisitadores> CasaisVisitadores
        {
            get
            {
                if ((_CasaisVisitadores == null))
                {
                    _CasaisVisitadores = base.CreateObjectSet<CasaisVisitadores>("CasaisVisitadores");
                }
                return _CasaisVisitadores;
            }
        }
        private ObjectSet<CasaisVisitadores> _CasaisVisitadores;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Inscricoes> Inscricoes
        {
            get
            {
                if ((_Inscricoes == null))
                {
                    _Inscricoes = base.CreateObjectSet<Inscricoes>("Inscricoes");
                }
                return _Inscricoes;
            }
        }
        private ObjectSet<Inscricoes> _Inscricoes;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Usuarios EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUsuarios(Usuarios usuarios)
        {
            base.AddObject("Usuarios", usuarios);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Encontros EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEncontros(Encontros encontros)
        {
            base.AddObject("Encontros", encontros);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CasaisConvidadores EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCasaisConvidadores(CasaisConvidadores casaisConvidadores)
        {
            base.AddObject("CasaisConvidadores", casaisConvidadores);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CasaisVisitadores EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCasaisVisitadores(CasaisVisitadores casaisVisitadores)
        {
            base.AddObject("CasaisVisitadores", casaisVisitadores);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Inscricoes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToInscricoes(Inscricoes inscricoes)
        {
            base.AddObject("Inscricoes", inscricoes);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EccModel", Name="CasaisConvidadores")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CasaisConvidadores : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CasaisConvidadores object.
        /// </summary>
        /// <param name="idCasalConvidador">Initial value of the IdCasalConvidador property.</param>
        public static CasaisConvidadores CreateCasaisConvidadores(global::System.Int32 idCasalConvidador)
        {
            CasaisConvidadores casaisConvidadores = new CasaisConvidadores();
            casaisConvidadores.IdCasalConvidador = idCasalConvidador;
            return casaisConvidadores;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdCasalConvidador
        {
            get
            {
                return _IdCasalConvidador;
            }
            set
            {
                if (_IdCasalConvidador != value)
                {
                    OnIdCasalConvidadorChanging(value);
                    ReportPropertyChanging("IdCasalConvidador");
                    _IdCasalConvidador = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdCasalConvidador");
                    OnIdCasalConvidadorChanged();
                }
            }
        }
        private global::System.Int32 _IdCasalConvidador;
        partial void OnIdCasalConvidadorChanging(global::System.Int32 value);
        partial void OnIdCasalConvidadorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NomeEle
        {
            get
            {
                return _NomeEle;
            }
            set
            {
                OnNomeEleChanging(value);
                ReportPropertyChanging("NomeEle");
                _NomeEle = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NomeEle");
                OnNomeEleChanged();
            }
        }
        private global::System.String _NomeEle;
        partial void OnNomeEleChanging(global::System.String value);
        partial void OnNomeEleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NomeEla
        {
            get
            {
                return _NomeEla;
            }
            set
            {
                OnNomeElaChanging(value);
                ReportPropertyChanging("NomeEla");
                _NomeEla = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NomeEla");
                OnNomeElaChanged();
            }
        }
        private global::System.String _NomeEla;
        partial void OnNomeElaChanging(global::System.String value);
        partial void OnNomeElaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CelularEle
        {
            get
            {
                return _CelularEle;
            }
            set
            {
                OnCelularEleChanging(value);
                ReportPropertyChanging("CelularEle");
                _CelularEle = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CelularEle");
                OnCelularEleChanged();
            }
        }
        private global::System.String _CelularEle;
        partial void OnCelularEleChanging(global::System.String value);
        partial void OnCelularEleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CelularEla
        {
            get
            {
                return _CelularEla;
            }
            set
            {
                OnCelularElaChanging(value);
                ReportPropertyChanging("CelularEla");
                _CelularEla = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CelularEla");
                OnCelularElaChanged();
            }
        }
        private global::System.String _CelularEla;
        partial void OnCelularElaChanging(global::System.String value);
        partial void OnCelularElaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EmailEle
        {
            get
            {
                return _EmailEle;
            }
            set
            {
                OnEmailEleChanging(value);
                ReportPropertyChanging("EmailEle");
                _EmailEle = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EmailEle");
                OnEmailEleChanged();
            }
        }
        private global::System.String _EmailEle;
        partial void OnEmailEleChanging(global::System.String value);
        partial void OnEmailEleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String emailEla
        {
            get
            {
                return _emailEla;
            }
            set
            {
                OnemailElaChanging(value);
                ReportPropertyChanging("emailEla");
                _emailEla = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("emailEla");
                OnemailElaChanged();
            }
        }
        private global::System.String _emailEla;
        partial void OnemailElaChanging(global::System.String value);
        partial void OnemailElaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IgrejaEle
        {
            get
            {
                return _IgrejaEle;
            }
            set
            {
                OnIgrejaEleChanging(value);
                ReportPropertyChanging("IgrejaEle");
                _IgrejaEle = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IgrejaEle");
                OnIgrejaEleChanged();
            }
        }
        private global::System.String _IgrejaEle;
        partial void OnIgrejaEleChanging(global::System.String value);
        partial void OnIgrejaEleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IgrejaEla
        {
            get
            {
                return _IgrejaEla;
            }
            set
            {
                OnIgrejaElaChanging(value);
                ReportPropertyChanging("IgrejaEla");
                _IgrejaEla = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IgrejaEla");
                OnIgrejaElaChanged();
            }
        }
        private global::System.String _IgrejaEla;
        partial void OnIgrejaElaChanging(global::System.String value);
        partial void OnIgrejaElaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Equipe
        {
            get
            {
                return _Equipe;
            }
            set
            {
                OnEquipeChanging(value);
                ReportPropertyChanging("Equipe");
                _Equipe = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Equipe");
                OnEquipeChanged();
            }
        }
        private global::System.String _Equipe;
        partial void OnEquipeChanging(global::System.String value);
        partial void OnEquipeChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EccModel", Name="CasaisVisitadores")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CasaisVisitadores : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CasaisVisitadores object.
        /// </summary>
        /// <param name="casalId">Initial value of the CasalId property.</param>
        public static CasaisVisitadores CreateCasaisVisitadores(global::System.Int32 casalId)
        {
            CasaisVisitadores casaisVisitadores = new CasaisVisitadores();
            casaisVisitadores.CasalId = casalId;
            return casaisVisitadores;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CasalId
        {
            get
            {
                return _CasalId;
            }
            set
            {
                if (_CasalId != value)
                {
                    OnCasalIdChanging(value);
                    ReportPropertyChanging("CasalId");
                    _CasalId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CasalId");
                    OnCasalIdChanged();
                }
            }
        }
        private global::System.Int32 _CasalId;
        partial void OnCasalIdChanging(global::System.Int32 value);
        partial void OnCasalIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NomeEle
        {
            get
            {
                return _NomeEle;
            }
            set
            {
                OnNomeEleChanging(value);
                ReportPropertyChanging("NomeEle");
                _NomeEle = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NomeEle");
                OnNomeEleChanged();
            }
        }
        private global::System.String _NomeEle;
        partial void OnNomeEleChanging(global::System.String value);
        partial void OnNomeEleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NomeEla
        {
            get
            {
                return _NomeEla;
            }
            set
            {
                OnNomeElaChanging(value);
                ReportPropertyChanging("NomeEla");
                _NomeEla = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NomeEla");
                OnNomeElaChanged();
            }
        }
        private global::System.String _NomeEla;
        partial void OnNomeElaChanging(global::System.String value);
        partial void OnNomeElaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CelularEle
        {
            get
            {
                return _CelularEle;
            }
            set
            {
                OnCelularEleChanging(value);
                ReportPropertyChanging("CelularEle");
                _CelularEle = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CelularEle");
                OnCelularEleChanged();
            }
        }
        private global::System.String _CelularEle;
        partial void OnCelularEleChanging(global::System.String value);
        partial void OnCelularEleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CelularEla
        {
            get
            {
                return _CelularEla;
            }
            set
            {
                OnCelularElaChanging(value);
                ReportPropertyChanging("CelularEla");
                _CelularEla = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CelularEla");
                OnCelularElaChanged();
            }
        }
        private global::System.String _CelularEla;
        partial void OnCelularElaChanging(global::System.String value);
        partial void OnCelularElaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DtVisita
        {
            get
            {
                return _DtVisita;
            }
            set
            {
                OnDtVisitaChanging(value);
                ReportPropertyChanging("DtVisita");
                _DtVisita = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DtVisita");
                OnDtVisitaChanged();
            }
        }
        private Nullable<global::System.DateTime> _DtVisita;
        partial void OnDtVisitaChanging(Nullable<global::System.DateTime> value);
        partial void OnDtVisitaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Confirmou
        {
            get
            {
                return _Confirmou;
            }
            set
            {
                OnConfirmouChanging(value);
                ReportPropertyChanging("Confirmou");
                _Confirmou = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Confirmou");
                OnConfirmouChanged();
            }
        }
        private Nullable<global::System.Boolean> _Confirmou;
        partial void OnConfirmouChanging(Nullable<global::System.Boolean> value);
        partial void OnConfirmouChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> ConducaoPropria
        {
            get
            {
                return _ConducaoPropria;
            }
            set
            {
                OnConducaoPropriaChanging(value);
                ReportPropertyChanging("ConducaoPropria");
                _ConducaoPropria = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ConducaoPropria");
                OnConducaoPropriaChanged();
            }
        }
        private Nullable<global::System.Boolean> _ConducaoPropria;
        partial void OnConducaoPropriaChanging(Nullable<global::System.Boolean> value);
        partial void OnConducaoPropriaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Equipe
        {
            get
            {
                return _Equipe;
            }
            set
            {
                OnEquipeChanging(value);
                ReportPropertyChanging("Equipe");
                _Equipe = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Equipe");
                OnEquipeChanged();
            }
        }
        private global::System.String _Equipe;
        partial void OnEquipeChanging(global::System.String value);
        partial void OnEquipeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RestricaoAlimentar
        {
            get
            {
                return _RestricaoAlimentar;
            }
            set
            {
                OnRestricaoAlimentarChanging(value);
                ReportPropertyChanging("RestricaoAlimentar");
                _RestricaoAlimentar = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("RestricaoAlimentar");
                OnRestricaoAlimentarChanged();
            }
        }
        private global::System.String _RestricaoAlimentar;
        partial void OnRestricaoAlimentarChanging(global::System.String value);
        partial void OnRestricaoAlimentarChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ApelidoEle
        {
            get
            {
                return _ApelidoEle;
            }
            set
            {
                OnApelidoEleChanging(value);
                ReportPropertyChanging("ApelidoEle");
                _ApelidoEle = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ApelidoEle");
                OnApelidoEleChanged();
            }
        }
        private global::System.String _ApelidoEle;
        partial void OnApelidoEleChanging(global::System.String value);
        partial void OnApelidoEleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ApelidoEla
        {
            get
            {
                return _ApelidoEla;
            }
            set
            {
                OnApelidoElaChanging(value);
                ReportPropertyChanging("ApelidoEla");
                _ApelidoEla = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ApelidoEla");
                OnApelidoElaChanged();
            }
        }
        private global::System.String _ApelidoEla;
        partial void OnApelidoElaChanging(global::System.String value);
        partial void OnApelidoElaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Observacoes
        {
            get
            {
                return _Observacoes;
            }
            set
            {
                OnObservacoesChanging(value);
                ReportPropertyChanging("Observacoes");
                _Observacoes = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Observacoes");
                OnObservacoesChanged();
            }
        }
        private global::System.String _Observacoes;
        partial void OnObservacoesChanging(global::System.String value);
        partial void OnObservacoesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IdInscricao
        {
            get
            {
                return _IdInscricao;
            }
            set
            {
                OnIdInscricaoChanging(value);
                ReportPropertyChanging("IdInscricao");
                _IdInscricao = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdInscricao");
                OnIdInscricaoChanged();
            }
        }
        private Nullable<global::System.Int32> _IdInscricao;
        partial void OnIdInscricaoChanging(Nullable<global::System.Int32> value);
        partial void OnIdInscricaoChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EccModel", Name="Encontros")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Encontros : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Encontros object.
        /// </summary>
        /// <param name="encontroId">Initial value of the EncontroId property.</param>
        public static Encontros CreateEncontros(global::System.Int32 encontroId)
        {
            Encontros encontros = new Encontros();
            encontros.EncontroId = encontroId;
            return encontros;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 EncontroId
        {
            get
            {
                return _EncontroId;
            }
            set
            {
                if (_EncontroId != value)
                {
                    OnEncontroIdChanging(value);
                    ReportPropertyChanging("EncontroId");
                    _EncontroId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("EncontroId");
                    OnEncontroIdChanged();
                }
            }
        }
        private global::System.Int32 _EncontroId;
        partial void OnEncontroIdChanging(global::System.Int32 value);
        partial void OnEncontroIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nome
        {
            get
            {
                return _Nome;
            }
            set
            {
                OnNomeChanging(value);
                ReportPropertyChanging("Nome");
                _Nome = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Nome");
                OnNomeChanged();
            }
        }
        private global::System.String _Nome;
        partial void OnNomeChanging(global::System.String value);
        partial void OnNomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Local
        {
            get
            {
                return _Local;
            }
            set
            {
                OnLocalChanging(value);
                ReportPropertyChanging("Local");
                _Local = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Local");
                OnLocalChanged();
            }
        }
        private global::System.String _Local;
        partial void OnLocalChanging(global::System.String value);
        partial void OnLocalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DtInicial
        {
            get
            {
                return _DtInicial;
            }
            set
            {
                OnDtInicialChanging(value);
                ReportPropertyChanging("DtInicial");
                _DtInicial = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DtInicial");
                OnDtInicialChanged();
            }
        }
        private Nullable<global::System.DateTime> _DtInicial;
        partial void OnDtInicialChanging(Nullable<global::System.DateTime> value);
        partial void OnDtInicialChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DtFinal
        {
            get
            {
                return _DtFinal;
            }
            set
            {
                OnDtFinalChanging(value);
                ReportPropertyChanging("DtFinal");
                _DtFinal = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DtFinal");
                OnDtFinalChanged();
            }
        }
        private Nullable<global::System.DateTime> _DtFinal;
        partial void OnDtFinalChanging(Nullable<global::System.DateTime> value);
        partial void OnDtFinalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> EventoConfirmado
        {
            get
            {
                return _EventoConfirmado;
            }
            set
            {
                OnEventoConfirmadoChanging(value);
                ReportPropertyChanging("EventoConfirmado");
                _EventoConfirmado = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EventoConfirmado");
                OnEventoConfirmadoChanged();
            }
        }
        private Nullable<global::System.Boolean> _EventoConfirmado;
        partial void OnEventoConfirmadoChanging(Nullable<global::System.Boolean> value);
        partial void OnEventoConfirmadoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> EventoRealizado
        {
            get
            {
                return _EventoRealizado;
            }
            set
            {
                OnEventoRealizadoChanging(value);
                ReportPropertyChanging("EventoRealizado");
                _EventoRealizado = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EventoRealizado");
                OnEventoRealizadoChanged();
            }
        }
        private Nullable<global::System.Boolean> _EventoRealizado;
        partial void OnEventoRealizadoChanging(Nullable<global::System.Boolean> value);
        partial void OnEventoRealizadoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> QtdeCasais
        {
            get
            {
                return _QtdeCasais;
            }
            set
            {
                OnQtdeCasaisChanging(value);
                ReportPropertyChanging("QtdeCasais");
                _QtdeCasais = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("QtdeCasais");
                OnQtdeCasaisChanged();
            }
        }
        private Nullable<global::System.Int32> _QtdeCasais;
        partial void OnQtdeCasaisChanging(Nullable<global::System.Int32> value);
        partial void OnQtdeCasaisChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EccModel", Name="Inscricoes")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Inscricoes : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Inscricoes object.
        /// </summary>
        /// <param name="idInscricao">Initial value of the IdInscricao property.</param>
        /// <param name="idEncontro">Initial value of the IdEncontro property.</param>
        /// <param name="idCasal">Initial value of the idCasal property.</param>
        /// <param name="participou">Initial value of the Participou property.</param>
        public static Inscricoes CreateInscricoes(global::System.Int32 idInscricao, global::System.Int32 idEncontro, global::System.Int32 idCasal, global::System.Boolean participou)
        {
            Inscricoes inscricoes = new Inscricoes();
            inscricoes.IdInscricao = idInscricao;
            inscricoes.IdEncontro = idEncontro;
            inscricoes.idCasal = idCasal;
            inscricoes.Participou = participou;
            return inscricoes;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdInscricao
        {
            get
            {
                return _IdInscricao;
            }
            set
            {
                if (_IdInscricao != value)
                {
                    OnIdInscricaoChanging(value);
                    ReportPropertyChanging("IdInscricao");
                    _IdInscricao = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdInscricao");
                    OnIdInscricaoChanged();
                }
            }
        }
        private global::System.Int32 _IdInscricao;
        partial void OnIdInscricaoChanging(global::System.Int32 value);
        partial void OnIdInscricaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdEncontro
        {
            get
            {
                return _IdEncontro;
            }
            set
            {
                OnIdEncontroChanging(value);
                ReportPropertyChanging("IdEncontro");
                _IdEncontro = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdEncontro");
                OnIdEncontroChanged();
            }
        }
        private global::System.Int32 _IdEncontro;
        partial void OnIdEncontroChanging(global::System.Int32 value);
        partial void OnIdEncontroChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idCasal
        {
            get
            {
                return _idCasal;
            }
            set
            {
                OnidCasalChanging(value);
                ReportPropertyChanging("idCasal");
                _idCasal = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idCasal");
                OnidCasalChanged();
            }
        }
        private global::System.Int32 _idCasal;
        partial void OnidCasalChanging(global::System.Int32 value);
        partial void OnidCasalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Participou
        {
            get
            {
                return _Participou;
            }
            set
            {
                OnParticipouChanging(value);
                ReportPropertyChanging("Participou");
                _Participou = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Participou");
                OnParticipouChanged();
            }
        }
        private global::System.Boolean _Participou;
        partial void OnParticipouChanging(global::System.Boolean value);
        partial void OnParticipouChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EccModel", Name="Usuarios")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Usuarios : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Usuarios object.
        /// </summary>
        /// <param name="idUsuario">Initial value of the IdUsuario property.</param>
        /// <param name="nome">Initial value of the Nome property.</param>
        /// <param name="isActive">Initial value of the IsActive property.</param>
        /// <param name="nivel">Initial value of the Nivel property.</param>
        public static Usuarios CreateUsuarios(global::System.Int32 idUsuario, global::System.String nome, global::System.Boolean isActive, global::System.Byte nivel)
        {
            Usuarios usuarios = new Usuarios();
            usuarios.IdUsuario = idUsuario;
            usuarios.Nome = nome;
            usuarios.IsActive = isActive;
            usuarios.Nivel = nivel;
            return usuarios;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdUsuario
        {
            get
            {
                return _IdUsuario;
            }
            set
            {
                if (_IdUsuario != value)
                {
                    OnIdUsuarioChanging(value);
                    ReportPropertyChanging("IdUsuario");
                    _IdUsuario = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IdUsuario");
                    OnIdUsuarioChanged();
                }
            }
        }
        private global::System.Int32 _IdUsuario;
        partial void OnIdUsuarioChanging(global::System.Int32 value);
        partial void OnIdUsuarioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nome
        {
            get
            {
                return _Nome;
            }
            set
            {
                OnNomeChanging(value);
                ReportPropertyChanging("Nome");
                _Nome = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nome");
                OnNomeChanged();
            }
        }
        private global::System.String _Nome;
        partial void OnNomeChanging(global::System.String value);
        partial void OnNomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsActive
        {
            get
            {
                return _IsActive;
            }
            set
            {
                OnIsActiveChanging(value);
                ReportPropertyChanging("IsActive");
                _IsActive = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsActive");
                OnIsActiveChanged();
            }
        }
        private global::System.Boolean _IsActive;
        partial void OnIsActiveChanging(global::System.Boolean value);
        partial void OnIsActiveChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte Nivel
        {
            get
            {
                return _Nivel;
            }
            set
            {
                OnNivelChanging(value);
                ReportPropertyChanging("Nivel");
                _Nivel = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Nivel");
                OnNivelChanged();
            }
        }
        private global::System.Byte _Nivel;
        partial void OnNivelChanging(global::System.Byte value);
        partial void OnNivelChanged();

        #endregion

    
    }

    #endregion

    
}
